import '../styles/globals.css';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ExpandableChatDemo } from "@/components/ExpandableChatDemo";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark bg-gray-900 text-white min-h-screen flex flex-col">
        <Navbar />
        {children}
        <ExpandableChatDemo />
        <Footer />
      </body>
    </html>
  )
}
